import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import GetMeteorsData from '@/components/getMeteorsData'
import Header from '@/components/Header'

export default function Home(){

  useEffect(() => {
    console.log('00')
    document.addEventListener('scroll', scrollHandler)
    return function () {
        document.removeEventListener('scroll', scrollHandler)
    }
}, [])

  const scrollHandler = (e) => {
      console.log('scroll')
  }

  return (
    <div style={{backgroundColor:'black', height:'120vh', display:'flex'}}>
      <Head>
        <title>Armaggedon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{backgroundColor:'black', height:'100vh', display:'block'}}>
        <Header/>
        <img src='/earth.png' style={{height: '80vh'}}/>
      </div>
      <div>
      <GetMeteorsData/>
      </div>
    </div>
  )
}
